### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by JavierArredondo** [shali7296/QAP_metaheuristica#1]
@shali7296 @sandrahy  💯

**Comment by shalinihenna** [comment]
Hellou @JavierArredondo <3

**Comment by sandrahy** [comment]
Salut

**Comment by SandraHernandezY** [comment]
Salut @JavierArredondo

**Comment by JavierArredondo** [comment]
![image](https://user-images.githubusercontent.com/19624900/91646244-373d4400-ea1b-11ea-9bd4-e4f6da5de1eb.png)

**Comment by SandraHernandezY** [comment]
![Screenshot_25](https://user-images.githubusercontent.com/31117322/91646321-dbbf8600-ea1b-11ea-8225-096a7605329a.png)
